sudo: required
language: bash
services: docker
dist: trusty

branches: 
  only: 
    - master

before_install:
  - docker build -t eswork/redis .
  
script: 
  - docker run --name redis_server -d --restart=always eswork/redis; sleep 5
  - docker ps -a | grep -q redis_server
  - docker exec -it redis_server redis-cli -s /run/redis/redis.sock PING
